DO $$ BEGIN
  CREATE TYPE "CohortType" AS ENUM ('STANDARD_QA', 'GOOGLE_PLAY_14_DAY', 'LIVE_STRESS_DROP');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "HardwareIntegrity" AS ENUM ('VERIFIED_PHYSICAL_NODE', 'EMULATOR_FLAGGED', 'UNVERIFIED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE "AppCampaign"
  ADD COLUMN IF NOT EXISTS "cohortType" "CohortType" NOT NULL DEFAULT 'STANDARD_QA',
  ADD COLUMN IF NOT EXISTS "guaranteedDays" INTEGER,
  ADD COLUMN IF NOT EXISTS "syncGitHubRepo" TEXT,
  ADD COLUMN IF NOT EXISTS "hardwareStrict" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Submission"
  ADD COLUMN IF NOT EXISTS "hardwareStatus" "HardwareIntegrity" NOT NULL DEFAULT 'UNVERIFIED',
  ADD COLUMN IF NOT EXISTS "gpuRenderer" TEXT,
  ADD COLUMN IF NOT EXISTS "isTouchCapable" BOOLEAN,
  ADD COLUMN IF NOT EXISTS "batteryLevel" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "isLowPowerMode" BOOLEAN,
  ADD COLUMN IF NOT EXISTS "hardwareFlags" TEXT[] DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "githubIssueUrl" TEXT;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "github_token_encrypted" TEXT;
