ALTER TYPE "SocialPlatform" ADD VALUE IF NOT EXISTS 'TIKTOK';
ALTER TYPE "SocialQueueStatus" ADD VALUE IF NOT EXISTS 'MANUAL' AFTER 'PENDING_APPROVAL';
ALTER TABLE "social_queue" ADD COLUMN IF NOT EXISTS "link_url" VARCHAR(500);
ALTER TABLE "social_queue" ADD COLUMN IF NOT EXISTS "video_script" JSONB;
