"use client";

import { useState } from "react";
import Link from "next/link";
import { clipTerms, draftStatuses, fundedStatuses } from "@/lib/clipper-rules";
import { applyToClip, checkClipTikTok, decideClipApplication, decideClipDraft, fundClip, manuallyVerifyClip, openClipDispute, refundClip, releaseClip, resumeClipDispute, sendClipDraft, sendClipMessage, sendClipPublication, setClipApplications, withdrawClip } from "@/app/actions/clipperActions";
import { ClipperForm, ClipReviewVideo, ClipRoomRefresh, ClipUpload, clipInputClass } from "@/components/clipper-controls";
import { MemberAction } from "@/components/member-action";
import { formatCents } from "@/lib/utils";

export type ClipRoomCampaign = { id: string; title: string; appUrl: string; brief: string; platform: string; feeCents: number; minimumRep: number; revisionLimit: number; deliveryDays: number; liveDays: number; open: boolean; developer: { username: string } };
export type ClipAgreementView = {
  id: string; creatorId: string; status: string; note: string; feeCents: number; chargeCents: number; revisionCount: number; reviewNote: string | null; dueAt: string | null; reviewDueAt: string | null; publishDueAt: string | null; fundedAt: string | null; paidAt: string | null; licenseEndsAt: string | null;
  draftId: string | null; approvedDraftId: string | null; proofId: string | null; publicationUrl: string | null; publicationCode: string; verificationMethod: string | null; disputeReason: string | null; moderationNote: string | null; termsAcceptedAt: string;
  creator: { username: string; xpPoints: number; clipProfile: { bio: string; specialties: string; portfolioUrl: string; socialUrl: string } | null; clipSocialAccounts: Array<{ displayName: string }> };
  assets: Array<{ id: string; name: string; kind: string; createdAt: string }>;
};
export type ClipRoomMessage = { id: string; body: string; createdAt: string; author: { username: string } };

export function ClipperRoom({ campaign, agreements, messages, briefAssets, members, roomAccess, developer, admin, storageEnabled, tikTokEnabled, olderCursor, viewerId }: {
  campaign: ClipRoomCampaign; agreements: ClipAgreementView[]; messages: ClipRoomMessage[]; briefAssets: Array<{ id: string; name: string }>; members: string[]; roomAccess: boolean; developer: boolean; admin: boolean; storageEnabled: boolean; tikTokEnabled: boolean; olderCursor: string | null; viewerId: string;
}) {
  return <div className="space-y-6">
    <section className="rounded-3xl border border-violet-400/25 bg-violet-500/5 p-5 sm:p-7"><p className="text-xs uppercase tracking-widest text-violet-300">{campaign.platform} / {campaign.developer.username}</p><h2 className="mt-3 text-2xl font-bold">{campaign.title}</h2><p className="mt-4 whitespace-pre-wrap break-words text-sm leading-7 text-neutral-300">{campaign.brief}</p><a href={campaign.appUrl} target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex min-h-11 items-center rounded-xl border border-stroke p-3 text-sm">Visit app website</a><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[`${formatCents(campaign.feeCents)} creator fee`, `${campaign.revisionLimit} revision rounds`, `${campaign.deliveryDays} days to draft`, `${campaign.liveDays} days public`].map((label) => <p key={label} className="rounded-xl border border-stroke p-3 text-sm">{label}</p>)}</div><p className="mt-4 text-xs leading-6 text-neutral-500">{campaign.minimumRep} REP required. No Discovery Pass bypass. No extra revisions without a new agreement. Deadline problems go to discussion/dispute, not automatic confiscation of funds.</p><p className="mt-3 text-xs leading-6 text-neutral-500">{clipTerms}</p>{developer ? <div className="mt-4"><MemberAction action={() => setClipApplications(campaign.id, !campaign.open)}>{campaign.open ? "Close new applications" : "Reopen applications"}</MemberAction></div> : null}</section>
    {!developer && !admin && !agreements.length && campaign.open ? <section className="rounded-2xl border border-stroke p-5"><h3 className="mb-4 text-lg font-bold">Apply as a Clipper</h3><ClipperForm label="Accept terms & apply" action={async (data) => applyToClip(campaign.id, String(data.get("note")), data.get("agree") === "on")}>
      <label className="block text-sm">Why your audience fits<textarea required name="note" minLength={20} maxLength={1500} rows={4} className={clipInputClass} placeholder="Your audience, sample concepts, experience, and social platform." /></label>
      <label className="flex items-start gap-3 text-sm leading-6"><input required type="checkbox" name="agree" className="mt-1 size-5 shrink-0" /><span>I accept the fixed fee, included revisions, delivery window, {campaign.liveDays}-day public-post requirement, sponsorship disclosure, and creator-owned 90-day organic license. I will not begin work until payment is confirmed funded.</span></label>
    </ClipperForm></section> : null}
    {agreements.length ? <section className="space-y-4"><h3 className="text-xl font-bold">{developer || admin ? "Creator agreements & private reviews" : "Your agreement"}</h3>{agreements.map((agreement) => <Agreement key={agreement.id} item={agreement} campaign={campaign} developer={developer} admin={admin} creator={agreement.creatorId === viewerId} storageEnabled={storageEnabled} tikTokEnabled={tikTokEnabled} />)}</section> : null}
    {roomAccess ? <div className="grid items-start gap-6 lg:grid-cols-[1fr_280px]"><section className="min-w-0 rounded-2xl border border-stroke p-5"><h3 className="text-xl font-bold">Campaign room</h3><div className="mt-3"><ClipRoomRefresh /></div><div className="my-5 space-y-4">{messages.map((message) => <article key={message.id} className="rounded-xl bg-surface p-4"><p className="text-sm font-semibold">{message.author.username}<span className="ml-2 text-xs font-normal text-neutral-500">{new Date(message.createdAt).toLocaleString()}</span></p><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-neutral-300">{message.body}</p></article>)}{!messages.length ? <p className="text-sm text-neutral-500">Start with a welcome, the app story, and reference material. Never share credentials or private customer data.</p> : null}</div>{olderCursor ? <Link href={`/clippers/${campaign.id}?before=${encodeURIComponent(olderCursor)}`} className="mb-4 inline-flex min-h-11 items-center text-sm text-violet-300">Earlier messages</Link> : null}<ClipperForm label="Send room message" action={async (data) => sendClipMessage(campaign.id, String(data.get("message")))}><label className="block text-sm">Message the campaign group<textarea required name="message" minLength={1} maxLength={2000} rows={3} className={clipInputClass} /></label></ClipperForm></section>
      <aside className="min-w-0 space-y-5"><section className="rounded-2xl border border-stroke p-5"><h3 className="font-bold">Invited members</h3><p className="mt-3 text-sm leading-7 text-neutral-400">{members.join(", ")}</p></section><section className="rounded-2xl border border-stroke p-5"><h3 className="mb-4 font-bold">Shared references</h3><div className="mb-4 space-y-2">{briefAssets.map((asset) => <a key={asset.id} href={`/api/clippers/assets/${asset.id}`} target="_blank" rel="noopener noreferrer" className="block min-h-11 break-words rounded-lg border border-stroke p-3 text-sm">{asset.name}</a>)}</div>{developer ? <ClipUpload campaignId={campaign.id} kind="BRIEF" enabled={storageEnabled} /> : <p className="text-xs leading-6 text-neutral-500">Developer-provided images and videos stay inside this invited group.</p>}</section></aside>
    </div> : <p className="rounded-xl border border-dashed border-stroke p-5 text-sm text-neutral-400">The group room opens only after the developer accepts your application. Drafts and publication evidence remain private to your agreement.</p>}
  </div>;
}

function Agreement({ item, campaign, developer, admin, creator, storageEnabled, tikTokEnabled }: { item: ClipAgreementView; campaign: ClipRoomCampaign; developer: boolean; admin: boolean; creator: boolean; storageEnabled: boolean; tikTokEnabled: boolean }) {
  const [proofId, setProofId] = useState(item.proofId || "");
  const profile = item.creator.clipProfile;
  const proofAssets = item.assets.filter((asset) => asset.kind === "PROOF");
  return <article className="min-w-0 space-y-5 rounded-2xl border border-stroke bg-surface p-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h4 className="text-lg font-bold">{item.creator.username}</h4><p className="mt-1 text-xs text-neutral-500">{item.creator.xpPoints} REP / Terms accepted {new Date(item.termsAcceptedAt).toLocaleDateString()}</p></div><span className="rounded-lg border border-violet-400/30 px-3 py-2 text-xs text-violet-200">{item.status.replaceAll("_", " ")}</span></div>
    <p className="text-sm leading-6 text-neutral-400">{item.note}</p>
    {(developer || admin) && profile ? <details><summary className="cursor-pointer text-sm text-violet-200">Creator background & samples</summary><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-6">{profile.bio}</p><p className="mt-2 text-xs text-neutral-400">{profile.specialties}</p><div className="mt-3 flex flex-wrap gap-3"><a href={profile.portfolioUrl} target="_blank" rel="noopener noreferrer" className="min-h-11 rounded-xl border border-stroke p-3 text-sm">Portfolio (self-reported)</a><a href={profile.socialUrl} target="_blank" rel="noopener noreferrer" className="min-h-11 rounded-xl border border-stroke p-3 text-sm">Social profile (self-reported)</a></div><p className="mt-3 text-xs text-neutral-500">{item.creator.clipSocialAccounts[0] ? `Connected TikTok ownership: ${item.creator.clipSocialAccounts[0].displayName}` : "No API-connected TikTok account. Social background requires manual review."}</p></details> : null}
    <p className="text-sm text-amber-300">{formatCents(item.feeCents)} creator fee / {formatCents(item.chargeCents)} developer total / {item.revisionCount} of {campaign.revisionLimit} revisions used</p>
    {item.dueAt ? <p className="text-xs text-neutral-400">Draft due {new Date(item.dueAt).toLocaleString()}</p> : null}
    {item.reviewDueAt ? <p className="text-xs text-neutral-400">Developer review / release due {new Date(item.reviewDueAt).toLocaleString()}. Escalate overdue work through the dispute controls; no automatic payout or refund.</p> : null}
    {item.publishDueAt ? <p className="text-xs text-neutral-400">Approved video publication due {new Date(item.publishDueAt).toLocaleString()}</p> : null}
    {item.reviewNote ? <p className="whitespace-pre-wrap break-words rounded-xl border border-amber-400/20 p-4 text-sm leading-6">Developer review: {item.reviewNote}</p> : null}
    {item.moderationNote ? <p className="whitespace-pre-wrap break-words text-sm text-violet-200">Administrator decision: {item.moderationNote}</p> : null}
    {developer && item.status === "APPLIED" ? <div className="flex flex-wrap gap-3"><MemberAction action={() => decideClipApplication(item.id, true)}>Accept & invite</MemberAction><MemberAction action={() => decideClipApplication(item.id, false)}>Decline</MemberAction></div> : null}
    {developer && ["ACCEPTED", "FUNDING"].includes(item.status) ? <ClipperForm label="Pre-fund creator agreement" action={async (data) => { const url = await fundClip(item.id, data.get("agree") === "on"); window.location.assign(url); return "Opening Stripe checkout."; }}><label className="flex items-start gap-3 text-sm leading-6"><input required name="agree" type="checkbox" className="mt-1 size-5 shrink-0" /><span>I agree to the fixed creator fee and campaign terms. Payment funds this agreement; it is not legal escrow. No paid-ad rights or guaranteed performance are included.</span></label></ClipperForm> : null}
    {creator && ["APPLIED", "ACCEPTED", "FUNDING"].includes(item.status) ? <p className="rounded-xl border border-amber-400/20 p-4 text-sm text-amber-200">Do not start work yet. Wait for FUNDED. If funding is blocked, finish Stripe setup in Account.</p> : null}
    {creator && ["APPLIED", "ACCEPTED"].includes(item.status) ? <MemberAction action={() => withdrawClip(item.id)}>Withdraw before funding</MemberAction> : null}
    {creator && draftStatuses.includes(item.status) ? <ClipUpload campaignId={campaign.id} engagementId={item.id} kind="DRAFT" enabled={storageEnabled} onComplete={(id) => sendClipDraft(item.id, id)} /> : null}
    {item.draftId ? <div><h5 className="mb-3 font-semibold">Latest draft</h5><ClipReviewVideo assetId={item.draftId} code={item.publicationCode} />{item.assets.filter((asset) => asset.kind === "DRAFT" && asset.id !== item.draftId).length ? <details className="mt-3"><summary className="min-h-11 cursor-pointer py-3 text-sm text-neutral-400">Previous draft versions</summary>{item.assets.filter((asset) => asset.kind === "DRAFT" && asset.id !== item.draftId).map((asset) => <div key={asset.id} className="mt-4"><p className="mb-2 text-xs text-neutral-500">{new Date(asset.createdAt).toLocaleString()} / {asset.name}</p><ClipReviewVideo assetId={asset.id} code={item.publicationCode} /></div>)}</details> : null}</div> : null}
    {developer && item.status === "DRAFT_SUBMITTED" ? <div className="space-y-4"><ClipperForm label="Request specific tweaks" disabled={item.revisionCount >= campaign.revisionLimit} action={async (data) => decideClipDraft(item.id, false, String(data.get("note")))}><label className="block text-sm">Revision instructions<textarea required name="note" minLength={12} maxLength={1500} rows={3} className={clipInputClass} /></label></ClipperForm><MemberAction action={() => decideClipDraft(item.id, true, "")}>Approve this video version for publication</MemberAction></div> : null}
    {creator && ["DRAFT_APPROVED", "PROOF_SUBMITTED"].includes(item.status) ? <div className="space-y-5 rounded-xl border border-violet-400/20 p-4"><h5 className="font-bold">Publish the approved clean video</h5><p className="text-sm leading-6 text-neutral-400">Publish yourself on {campaign.platform}. Include <strong className="break-all text-violet-200">{item.publicationCode}</strong> in the caption, use the platform&apos;s paid partnership / sponsorship disclosure, and keep it public for {campaign.liveDays} days. Do not publish the SeedEnv review overlay. No automatic social posting is performed.</p><ClipUpload campaignId={campaign.id} engagementId={item.id} kind="PROOF" enabled={storageEnabled} onComplete={async (id) => { setProofId(id); return "Evidence uploaded. Select it below and submit the public post URL."; }} /><ClipperForm label="Submit publication evidence" action={async (data) => sendClipPublication(item.id, String(data.get("url")), String(data.get("proofId")), data.get("disclosure") === "on")}>
      <label className="block text-sm">Full public video URL<input required type="url" name="url" defaultValue={item.publicationUrl || ""} className={clipInputClass} /></label>
      <label className="block text-sm">Evidence screenshot<select required name="proofId" value={proofId} onChange={(event) => setProofId(event.target.value)} className={clipInputClass}><option value="">Choose uploaded evidence</option>{proofAssets.map((asset) => <option key={asset.id} value={asset.id}>{asset.name}</option>)}{proofId && !proofAssets.some((asset) => asset.id === proofId) ? <option value={proofId}>New evidence screenshot</option> : null}</select></label>
      <label className="flex items-start gap-3 text-sm leading-6"><input required name="disclosure" type="checkbox" className="mt-1 size-5 shrink-0" /><span>The public post is my approved video, includes the campaign code and required paid-content disclosure, and uses media I am allowed to publish.</span></label>
    </ClipperForm></div> : null}
    {item.publicationUrl ? <div className="flex flex-wrap gap-3"><a href={item.publicationUrl} target="_blank" rel="noopener noreferrer" className="min-h-11 break-words rounded-xl border border-stroke p-3 text-sm">View public post</a>{item.proofId ? <a href={`/api/clippers/assets/${item.proofId}`} target="_blank" rel="noopener noreferrer" className="min-h-11 rounded-xl border border-stroke p-3 text-sm">View private publication evidence</a> : null}</div> : null}
    {creator && item.status === "PROOF_SUBMITTED" && campaign.platform === "TIKTOK" && tikTokEnabled ? <MemberAction action={() => checkClipTikTok(item.id)}>Verify TikTok ownership & caption</MemberAction> : null}
    {developer && item.status === "PROOF_SUBMITTED" ? <ClipperForm label="Record manual verification" action={async (data) => manuallyVerifyClip(item.id, String(data.get("note")), data.get("confirmed") === "on")}><label className="block text-sm">Verification notes<textarea required name="note" minLength={20} maxLength={1500} rows={3} placeholder="Account ownership evidence, post/caption code, disclosure, and match to approved draft." className={clipInputClass} /></label><label className="flex items-start gap-3 text-sm leading-6"><input required type="checkbox" name="confirmed" className="mt-1 size-5 shrink-0" /><span>I checked the public post, creator ownership, caption code, sponsorship disclosure, and video against the approved draft. This is manual verification, not API proof.</span></label></ClipperForm> : null}
    {item.verificationMethod ? <p className="text-sm text-emerald-300">Verification: {item.verificationMethod.replaceAll("_", " ")}. API checks do not prove visual identity to the approved draft.</p> : null}
    {developer && ["VERIFIED", "PAYMENT_PENDING"].includes(item.status) ? <ClipperForm label={item.status === "PAYMENT_PENDING" ? "Retry / reconcile same payment" : "Release agreed creator fee"} action={async (data) => releaseClip(item.id, data.get("confirmed") === "on")}><label className="flex items-start gap-3 text-sm leading-6"><input required name="confirmed" type="checkbox" className="mt-1 size-5 shrink-0" /><span>I checked the live video matches the approved draft and posting requirements. Release the agreed fee once; retries reconcile the same Stripe transfer.</span></label></ClipperForm> : null}
    {item.status === "PAID" ? <p className="rounded-xl border border-emerald-500/30 p-4 text-sm leading-6 text-emerald-200">Creator fee transferred to Stripe {item.paidAt ? new Date(item.paidAt).toLocaleDateString() : ""}. Organic repost license ends {item.licenseEndsAt ? new Date(item.licenseEndsAt).toLocaleDateString() : ""}. Bank payout timing is controlled by Stripe. Paid ads are not included.</p> : null}
    {item.disputeReason ? <p className="whitespace-pre-wrap break-words rounded-xl border border-rose-400/30 p-4 text-sm leading-6 text-rose-200">Dispute / payment review: {item.disputeReason}</p> : null}
    {(creator || developer) && (fundedStatuses.includes(item.status) || item.status === "PAID") && item.status !== "DISPUTED" ? <details><summary className="min-h-11 cursor-pointer py-3 text-sm text-neutral-400">Need help? Open an agreement dispute</summary><ClipperForm label="Flag agreement for administrator review" action={async (data) => openClipDispute(item.id, String(data.get("reason")))}><label className="block text-sm">Describe the issue<textarea required name="reason" minLength={20} maxLength={1500} rows={3} className={clipInputClass} /></label></ClipperForm></details> : null}
    {(developer && ["FUNDED", "CANCEL_PENDING"].includes(item.status)) || (admin && ["FUNDED", "DISPUTED", "CANCEL_PENDING"].includes(item.status)) ? <details><summary className="min-h-11 cursor-pointer py-3 text-sm text-neutral-400">{admin ? "Administrator refund decision" : "Cancel before creator upload"}</summary><ClipperForm label="Cancel & refund full funding" action={async (data) => refundClip(item.id, String(data.get("reason")))}><label className="block text-sm">Recorded cancellation / refund reason<textarea required name="reason" minLength={20} maxLength={1500} rows={3} className={clipInputClass} /></label><p className="text-xs leading-6 text-neutral-500">Developer cancellation is blocked once draft upload starts. Administrator review is required thereafter. No refund shortcut is available after payout begins.</p></ClipperForm></details> : null}
    {admin && (item.status === "DISPUTED" || (item.status === "PAYMENT_PENDING" && item.disputeReason)) ? <ClipperForm label="Record decision & resume agreement" action={async (data) => resumeClipDispute(item.id, String(data.get("note")))}><label className="block text-sm">Administrator resolution<textarea required name="note" minLength={20} maxLength={1500} rows={3} className={clipInputClass} /></label></ClipperForm> : null}
  </article>;
}
