import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { isDeveloper, socialMemberSelect } from "@/lib/social-connections";
import { publicProfilePath, isPublicHandle } from "@/lib/public-profile";
import { FollowControls } from "@/components/social-controls";

export async function ConnectionSettings({ memberId, page = 1 }: { memberId: string; page?: number }) {
  const [following, followers] = await Promise.all([
    prisma.userFollow.findMany({ where: { followerId: memberId }, orderBy: [{ createdAt: "desc" }, { followingId: "asc" }], skip: (page - 1) * 20, take: 21, include: { following: { select: socialMemberSelect } } }),
    prisma.userFollow.findMany({ where: { followingId: memberId }, orderBy: [{ createdAt: "desc" }, { followerId: "asc" }], skip: (page - 1) * 20, take: 21, include: { follower: { select: socialMemberSelect } } }),
  ]);
  return <section className="space-y-5"><h1 className="text-2xl font-semibold">Connections</h1><p className="text-sm text-zinc-400">Keep up with developers and testers. Developer emails are opt-in per follow; tester follows never send emails.</p><div className="grid gap-5 lg:grid-cols-2"><section><h2 className="text-lg font-semibold">Following</h2>{!following.length ? <p className="mt-3 text-sm text-zinc-500">Not following anyone yet. Open a cohort developer or Launch Circle profile to connect.</p> : null}{following.slice(0, 20).map(follow => <article className="mt-4 space-y-3 rounded-xl border border-white/10 bg-[#12161F] p-5" key={follow.followingId}><h3 className="font-semibold">{isPublicHandle(follow.following.username) ? <Link href={publicProfilePath(follow.following.username)}>@{follow.following.username}</Link> : follow.following.username}</h3><FollowControls targetId={follow.followingId} developer={isDeveloper(follow.following)} signedIn own={false} following emailUpdates={follow.emailUpdates} /></article>)}</section><section><h2 className="text-lg font-semibold">Followers</h2>{!followers.length ? <p className="mt-3 text-sm text-zinc-500">No followers yet.</p> : null}{followers.slice(0, 20).map(follow => <article key={follow.followerId} className="mt-4 rounded-xl border border-white/10 p-5"><span className="text-sm">{isPublicHandle(follow.follower.username) ? <Link href={publicProfilePath(follow.follower.username)}>@{follow.follower.username}</Link> : follow.follower.username}</span><Link className="ml-4 inline-flex min-h-11 items-center text-sm text-emerald-300" href={`/messages?to=${follow.followerId}`}>Message</Link></article>)}</section></div><nav aria-label="Connection pages" className="flex gap-4">{page > 1 ? <Link href={`/account?tab=connections&page=${page - 1}`}>Previous</Link> : null}{following.length > 20 || followers.length > 20 ? <Link href={`/account?tab=connections&page=${page + 1}`}>Next</Link> : null}</nav></section>;
}
