import "dotenv/config";
import test, { mock } from "node:test";
import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import type { User } from "@prisma/client";
import { prisma } from "../lib/prisma";
import { assertProofEditable, startProofRevision } from "../lib/submission-lifecycle";
import nextConfig from "../next.config";

test("proof editing requires an explicit revision start and a live editing window", () => {
  const original = { expiresAt: new Date(Date.now() + 60000), feedbackText: "Original feedback", proofImageUrl: "proof:original", revisionRequestedAt: null, revisionStartedAt: null };
  assert.throws(() => assertProofEditable(original), /already awaiting review/);
  const requested = { ...original, revisionRequestedAt: new Date() };
  assert.throws(() => assertProofEditable(requested), /Start your requested revision/);
  assert.doesNotThrow(() => assertProofEditable({ ...requested, revisionStartedAt: new Date() }));
  assert.throws(() => assertProofEditable({ ...requested, revisionStartedAt: new Date(), expiresAt: new Date(Date.now() - 1) }), /window expired/);
  const encodedScreenshot = Buffer.alloc(5 * 1024 * 1024).toString("base64");
  assert.equal(nextConfig.experimental?.serverActions?.bodySizeLimit, "8mb");
  assert.ok(Buffer.byteLength(JSON.stringify({ proofImageBase64: encodedScreenshot, feedbackText: "f".repeat(2000), crashLogs: "c".repeat(20000), networkLogs: "n".repeat(20000) })) < 8 * 1024 * 1024);
});

test("launch journeys use real rollback-only database records and mocked providers", { skip: process.env.RUN_LAUNCH_DB_TESTS !== "1" }, async () => {
  const marker = `launch-${randomUUID()}`;
  const rollback = new Error("Intentional launch fixture rollback");
  const modules: Array<ReturnType<typeof mock.module>> = [];
  let member: User;
  let signedIn = true;
  let uploads = 0;
  const revalidated: string[] = [];
  const session = {
    id: `cs_${marker}`, mode: "payment", status: "complete", payment_status: "unpaid",
    currency: "usd", amount_total: 1000, payment_intent: `pi_${marker}`,
    metadata: { type: "SEEDENV_CAMPAIGN_ESCROW", campaignId: "", developerId: "" },
  };
  modules.push(mock.module("../lib/member.ts", { namedExports: { requireMember: async (role?: string) => {
    if (role && member.role !== role && member.role !== "ADMIN") throw new Error("Wrong workspace.");
    return member;
  } } }));
  modules.push(mock.module("../app/api/auth/[...nextauth]/route.ts", { namedExports: { authOptions: {} } }));
  modules.push(mock.module("next-auth", { namedExports: { getServerSession: async () => signedIn ? { user: { id: member.id } } : null } }));
  modules.push(mock.module("../lib/storage.ts", { namedExports: { uploadProofImage: async () => { uploads++; return "proof:mock-replacement"; }, getProofImageUrl: async () => "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/a9sAAAAASUVORK5CYII=" } }));
  modules.push(mock.module("../lib/stripe.ts", { namedExports: { getStripe: () => ({ checkout: { sessions: { retrieve: async () => session } } }) } }));
  modules.push(mock.module("../lib/notifications.ts", { namedExports: { notificationEnabled: () => false, sendNotificationEmail: async () => { throw new Error("No emails may be sent by this test."); } } }));
  modules.push(mock.module("next/cache", { namedExports: { revalidatePath: (path: string) => { revalidated.push(path); } } }));
  try {
    await assert.rejects(prisma.$transaction(async (tx) => {
      modules.push(mock.module("../lib/prisma.ts", { namedExports: { prisma: new Proxy(tx, { get: (target, key) => key === "$transaction" ? async (work: (database: typeof tx) => Promise<unknown>) => work(tx) : Reflect.get(target, key) }) } }));
      const { awardDailyCheckIn } = await import("../lib/quest-ledger");
      const { requestSubmissionRevision, startSubmissionRevision, submitTaskProof, approveSubmission, rejectSubmission } = await import("../app/actions/submissionActions");
      const { handleStripeWebhook } = await import("../lib/campaign-payments");
      const { publishComment, hideCommunityContent } = await import("../app/actions/communityActions");
      const { GET: getPrivateProof } = await import("../app/api/submissions/[id]/proof/route");
      const developer = await tx.user.create({ data: { email: `${marker}-dev@example.invalid`, role: "DEVELOPER" } });
      const tester = await tx.user.create({ data: { email: `${marker}-tester@example.invalid`, role: "TESTER" } });
      const stranger = await tx.user.create({ data: { email: `${marker}-stranger@example.invalid`, role: "TESTER" } });
      member = tester;
      assert.equal(await awardDailyCheckIn(tester.id), true);
      assert.equal(await awardDailyCheckIn(tester.id), false);
      assert.equal((await tx.user.findUniqueOrThrow({ where: { id: tester.id } })).questXp, 5);
      assert.equal(revalidated.length, 0, "render-safe daily credit must not invalidate caches");
      const campaign = await tx.appCampaign.create({ data: { developerId: developer.id, title: "Launch fixture", platform: "WEB_STAGING", appUrl: "https://example.invalid", targetVibe: "Test", description: "Rollback-only launch fixture", totalBudgetUsd: 10, bountyPerTaskUsd: 1, platformFeeUsd: 0.8, totalSlots: 5, claimedSlots: 1, status: "ACTIVE", expiresAt: new Date(Date.now() + 86400000) } });
      const original = await tx.submission.create({ data: { campaignId: campaign.id, testerId: tester.id, payoutCents: 100, expiresAt: new Date(Date.now() - 3600000), feedbackText: "Original feedback preserved.", proofImageUrl: "proof:original", proofImageHash: "original-hash", deviceModel: "Original phone" } });
      const proofRequest = new Request(`http://localhost/api/submissions/${original.id}/proof`);
      const proofParams = { params: Promise.resolve({ id: original.id }) };
      signedIn = false;
      assert.equal((await getPrivateProof(proofRequest, proofParams)).status, 401);
      signedIn = true;
      member = stranger;
      assert.equal((await getPrivateProof(proofRequest, proofParams)).status, 404);
      member = tester;
      const proofResponse = await getPrivateProof(proofRequest, proofParams);
      assert.equal(proofResponse.status, 200);
      assert.equal(proofResponse.headers.get("cache-control"), "private, no-store");
      assert.equal(proofResponse.headers.get("content-type"), "image/png");
      assert.equal((await proofResponse.arrayBuffer()).byteLength, 68);
      member = developer;
      await requestSubmissionRevision(original.id, "Please clarify the reproduction steps.");
      const requested = await tx.submission.findUniqueOrThrow({ where: { id: original.id } });
      assert.ok(requested.revisionRequestedAt);
      assert.equal(requested.revisionStartedAt, null);
      assert.equal(requested.expiresAt.getTime(), original.expiresAt.getTime());
      assert.equal(requested.proofImageUrl, original.proofImageUrl);
      await assert.rejects(approveSubmission(original.id), /requested revision/);
      await assert.rejects(requestSubmissionRevision(original.id, "A second revision request."), /outstanding/);
      member = stranger;
      await assert.rejects(startSubmissionRevision(original.id), /your submission/);
      member = tester;
      await assert.rejects(submitTaskProof(original.id, { feedbackText: "Updated but not started yet." }), /Start your requested revision/);
      const startTime = Date.now();
      const started = await startSubmissionRevision(original.id);
      assert.ok(started.expiresAt.getTime() >= startTime + 1800000 && started.expiresAt.getTime() <= Date.now() + 1800000);
      assert.equal(started.deviceModel, "Original phone");
      const resumed = await startProofRevision(tx, tester.id, original.id);
      assert.equal(resumed.expiresAt.getTime(), started.expiresAt.getTime());
      await tx.submission.update({ where: { id: original.id }, data: { expiresAt: new Date(Date.now() - 1) } });
      await assert.rejects(submitTaskProof(original.id, { feedbackText: "Updated after window expired." }), /window expired/);
      await startSubmissionRevision(original.id);
      await assert.rejects(submitTaskProof(original.id, { feedbackText: "Updated reproduction steps.", recordingUrl: "javascript:alert(1)" }));
      const revised = await submitTaskProof(original.id, { feedbackText: "Updated reproduction steps.", deviceModel: "Original phone", recordingUrl: "" });
      assert.equal(revised.proofImageUrl, original.proofImageUrl);
      assert.equal(revised.proofImageHash, original.proofImageHash);
      assert.equal(revised.revisionRequestedAt, null);
      assert.equal(uploads, 0);
      await assert.rejects(submitTaskProof(original.id, { feedbackText: "Double submit should fail." }), /already awaiting review/);
      member = developer;
      await requestSubmissionRevision(original.id, "Please replace the screenshot now.");
      member = tester;
      await startSubmissionRevision(original.id);
      const image = Buffer.alloc(5 * 1024 * 1024);
      Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]).copy(image);
      const hash = createHash("sha256").update(image).digest("hex");
      const oversized = Buffer.concat([image, Buffer.from([0])]);
      await assert.rejects(submitTaskProof(original.id, { feedbackText: "Replacement proof feedback.", proofImageBase64: oversized.toString("base64"), proofImageMimeType: "image/png" }), /under 5MB/);
      await assert.rejects(submitTaskProof(original.id, { feedbackText: "Replacement proof feedback.", proofImageBase64: image.toString("base64"), proofImageMimeType: "image/png", proofImageHash: "invalid-hash-value" }), /hash did not match/);
      await submitTaskProof(original.id, { feedbackText: "Replacement proof feedback.", proofImageBase64: image.toString("base64"), proofImageMimeType: "image/png", proofImageHash: hash });
      assert.equal(uploads, 1);
      assert.equal((await tx.submission.findUniqueOrThrow({ where: { id: original.id } })).proofImageHash, hash);
      assert.equal((await tx.appCampaign.findUniqueOrThrow({ where: { id: campaign.id } })).claimedSlots, 1);
      member = developer;
      const approval = await approveSubmission(original.id);
      assert.equal(approval.payoutStatus, "PENDING");
      await assert.rejects(rejectSubmission(original.id, "Low Effort"), /Pending submission/);
      assert.equal((await tx.appCampaign.findUniqueOrThrow({ where: { id: campaign.id } })).claimedSlots, 1);
      assert.equal((await tx.appCampaign.findUniqueOrThrow({ where: { id: campaign.id } })).completedSlots, 1);
      assert.equal((await tx.user.findUniqueOrThrow({ where: { id: tester.id } })).walletBalanceCents, 0);
      assert.equal(await tx.walletTransaction.count({ where: { userId: tester.id, type: "BOUNTY_PAYOUT", status: "PENDING" } }), 1);
      await tx.appCampaign.update({ where: { id: campaign.id }, data: { claimedSlots: { increment: 1 } } });
      const other = await tx.submission.create({ data: { campaignId: campaign.id, testerId: stranger.id, payoutCents: 100, expiresAt: new Date(Date.now() + 60000), feedbackText: "Another tester's feedback", proofImageUrl: "proof:other" } });
      await rejectSubmission(other.id, "Low Effort");
      await assert.rejects(rejectSubmission(other.id, "Low Effort"), /Pending submission/);
      assert.equal((await tx.appCampaign.findUniqueOrThrow({ where: { id: campaign.id } })).claimedSlots, 1);

      const post = await tx.communityPost.create({ data: { authorId: developer.id, body: "A launch fixture app announcement." } });
      member = tester;
      await publishComment(post.id, "Useful discussion feedback.");
      assert.ok(revalidated.includes("/community/[id]"));
      const comment = await tx.communityComment.findFirstOrThrow({ where: { postId: post.id, authorId: tester.id } });
      member = stranger;
      await assert.rejects(hideCommunityContent(comment.id, "comment"), /Only the author/);
      member = tester;
      await hideCommunityContent(comment.id, "comment");
      assert.equal((await tx.communityComment.findUniqueOrThrow({ where: { id: comment.id } })).hidden, true);

      await tx.appCampaign.update({ where: { id: campaign.id }, data: { status: "ESCROW_PENDING" } });
      const deposit = await tx.walletTransaction.create({ data: { userId: developer.id, amountCents: 1000, type: "ESCROW_DEPOSIT", status: "PENDING", description: `Escrow deposit for ${campaign.title} (${campaign.id})` } });
      session.metadata.campaignId = campaign.id;
      session.metadata.developerId = developer.id;
      const event = { type: "checkout.session.completed", data: { object: { id: session.id } } };
      assert.deepEqual(await handleStripeWebhook(event), { awaitingPayment: true });
      session.payment_status = "paid";
      session.amount_total = 1;
      await assert.rejects(handleStripeWebhook(event), /amount or currency/);
      session.amount_total = 1000;
      session.currency = "eur";
      await assert.rejects(handleStripeWebhook(event), /amount or currency/);
      session.currency = "usd";
      session.metadata.developerId = tester.id;
      await assert.rejects(handleStripeWebhook(event), /ownership/);
      session.metadata.developerId = developer.id;
      assert.deepEqual(await handleStripeWebhook(event), { activated: true, campaignId: campaign.id });
      assert.deepEqual(await handleStripeWebhook(event), { duplicate: true, campaignId: campaign.id });
      assert.equal((await tx.walletTransaction.findUniqueOrThrow({ where: { id: deposit.id } })).stripePaymentId, session.payment_intent);
      await tx.appCampaign.update({ where: { id: campaign.id }, data: { status: "PAUSED" } });
      assert.deepEqual(await handleStripeWebhook(event), { duplicate: true, campaignId: campaign.id });
      assert.equal((await tx.appCampaign.findUniqueOrThrow({ where: { id: campaign.id } })).status, "PAUSED");
      await tx.appCampaign.update({ where: { id: campaign.id }, data: { status: "COMPLETED" } });
      assert.deepEqual(await handleStripeWebhook(event), { duplicate: true, campaignId: campaign.id });
      assert.equal((await tx.appCampaign.findUniqueOrThrow({ where: { id: campaign.id } })).status, "COMPLETED");
      await tx.appCampaign.update({ where: { id: campaign.id }, data: { status: "PAUSED" } });
      session.payment_intent = `pi_other_${marker}`;
      await assert.rejects(handleStripeWebhook(event), /not awaiting funding/);
      assert.equal((await tx.appCampaign.findUniqueOrThrow({ where: { id: campaign.id } })).status, "PAUSED");
      assert.ok(revalidated.includes("/dashboard") && revalidated.includes("/console"));
      throw rollback;
    }, { timeout: 60000 }), (error: unknown) => error === rollback);
    assert.equal(await prisma.user.count({ where: { email: { startsWith: marker } } }), 0);
  } finally {
    for (const moduleMock of modules.reverse()) moduleMock.restore();
    await prisma.$disconnect();
  }
});
