import Link from "next/link";
import { publicPageMetadata } from "@/lib/seo";

export const metadata = publicPageMetadata("Documentation", "SeedEnv TestFlight setup, telemetry format, cohort funding, validator guidelines, and Stripe payout documentation.", "/docs");

export default function DocumentationPage() {
  return <>
    <h1>SeedEnv Documentation</h1>
    <section id="testflight" className="scroll-mt-24"><h2>TestFlight Setup Guide</h2><p>Upload a testing build to App Store Connect, complete Apple&apos;s required beta review where applicable, and create an external-testing group. Supply a working TestFlight invitation link in your cohort brief. Include the supported device/OS versions, test accounts, and any sandbox credentials. Never include production passwords.</p><p><a href="https://developer.apple.com/testflight/" className="text-emerald-300 underline">Apple TestFlight documentation</a></p></section>
    <section id="telemetry" className="scroll-mt-24"><h2>Telemetry Format</h2><p>Reports should include device model, OS version, app build, reproduction steps, expected and observed results, and relevant proof. Screenshots, permitted screen recordings, and crash/network logs must exclude personal data, tokens, and credentials.</p><pre className="mt-5 overflow-auto rounded-lg border border-white/10 p-4 text-xs leading-6 text-zinc-300"><code>{JSON.stringify({ deviceModel: "iPhone 15 Pro", osVersion: "iOS 18", build: "1.4.0 (42)", steps: ["Open test invitation", "Sign in", "Return to invitation"], expected: "Invitation remains available", actual: "Redirect returns to home", attachments: ["reproduction.mp4", "redacted-crash.log"] }, null, 2)}</code></pre></section>
    <section id="escrow" className="scroll-mt-24"><h2>Escrow &amp; Fees</h2><p>SeedEnv adds a 5% platform fee to the tester reward pool: $100 in rewards plus $5 platform fee gives $105 total funding before separate Stripe fees where applicable. Cohorts activate only after signed payment confirmation. Approval and successful payment transfer are distinct events; pending transfers remain visible.</p><p><Link href="/console?view=billing" className="text-emerald-300 underline">Company billing and PDF receipts</Link></p></section>
    <section id="payouts" className="scroll-mt-24"><h2>Payout Schedule (Stripe)</h2><p>Connect Stripe Express to receive approved cohort payments. The connected account&apos;s live schedule determines bank payouts and settlement. Weekly payouts and 48-hour availability are not universal defaults. Tax forms, including US 1099 forms when applicable, depend on geography, eligibility, and the platform&apos;s Stripe tax configuration.</p><p><Link href="/dashboard/validator/payouts" className="text-emerald-300 underline">View connected bank and payout schedule</Link></p></section>
    <section id="guidelines" className="scroll-mt-24"><h2>Validator Guidelines &amp; NDA</h2><p>Use your own testing evidence, follow the cohort acceptance criteria, and report reproducible results. Keep unreleased builds and confidential developer details private. Platform confidentiality obligations are covered by the Terms of Service; a separate NDA must be agreed by the parties where required. SeedEnv does not generate a signed NDA by merely displaying this guide.</p><p><Link href="/terms" className="text-emerald-300 underline">Terms of Service</Link></p></section>
  </>;
}